# Generated by Django 2.2.6 on 2019-12-07 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('onboard_confirmed', models.BooleanField(default=False)),
                ('industry', multiselectfield.db.fields.MultiSelectField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting')], max_length=30)),
                ('role', models.CharField(default='Unknown', max_length=30)),
                ('major', models.CharField(default='Unknown', max_length=100)),
                ('year_in_school', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student'), ('Postdoc', 'Postdoc'), ('Not in School', 'Not in School')], default='Unknown', max_length=20)),
                ('is_matched', models.BooleanField(default=False)),
                ('has_request', models.BooleanField(default=False)),
                ('match_name', models.CharField(max_length=100)),
                ('is_sender', models.BooleanField(default=False)),
                ('time_matched', models.DateTimeField(auto_now=True)),
                ('is_waiting', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
