# Generated by Django 2.2.6 on 2019-11-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_photos'),
        ),
    ]
