# Generated by Django 2.2.6 on 2019-12-11 21:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0004_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='(None)', help_text='Contact phone number', max_length=31),
        ),
    ]
