# Generated by Django 2.2.7 on 2019-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0004_auto_20191108_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboard_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
