# Generated by Django 2.2.6 on 2019-11-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_profile_avatar'),
        ('onboard', '0005_profile_onboard_confirmed'),
    ]

    operations = [
    ]
