# Generated by Django 2.2.6 on 2019-11-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0006_merge_20191114_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
