# Generated by Django 3.0 on 2019-12-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0006_profile_match_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='match_filters',
        ),
    ]
