# Generated by Django 2.2.6 on 2019-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0007_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student'), ('Postdoc', 'Postdoc'), ('Not in School', 'Not in School')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting')], max_length=30),
        ),
    ]
