# Generated by Django 2.2.6 on 2019-11-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0009_auto_20191118_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
