# Generated by Django 2.2.6 on 2019-11-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0010_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_request',
            field=models.BooleanField(default=False),
        ),
    ]
