# Generated by Django 2.2.6 on 2019-12-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0011_profile_has_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='match_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
