# Generated by Django 3.0 on 2019-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0013_auto_20191220_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry_match',
            field=models.CharField(choices=[('None', 'None'), ('Consulting', 'Consulting'), ('Finance', 'Finance'), ('Technology', 'Technology')], default='Industry 1', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry_choice_1',
            field=models.CharField(choices=[('None', 'None'), ('Consulting', 'Consulting'), ('Finance', 'Finance'), ('Technology', 'Technology')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry_choice_2',
            field=models.CharField(choices=[('None', 'None'), ('Consulting', 'Consulting'), ('Finance', 'Finance'), ('Technology', 'Technology')], default='None', max_length=30),
        ),
    ]
