# Generated by Django 2.2.6 on 2019-12-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0013_auto_20191205_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_match',
            new_name='match_name',
        ),
    ]
