# Generated by Django 2.2.6 on 2019-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0014_auto_20191205_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
