# Generated by Django 2.2.6 on 2019-12-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0015_profile_is_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
