# Generated by Django 3.0 on 2019-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0020_auto_20191221_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry_match',
            field=models.CharField(choices=[('Industry 1', 'Industry 1'), ('Industry 2', 'Industry 2'), ('Both', 'Both'), ('None', 'Not Looking')], default='Industry 1', max_length=30),
        ),
    ]
