# Generated by Django 2.2.6 on 2020-01-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0026_profile_receive_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
