# Generated by Django 2.2.6 on 2020-01-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0032_profile_requested_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='requested_name',
            new_name='request_name',
        ),
    ]
