# Generated by Django 2.2.6 on 2020-01-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0033_auto_20200107_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='match_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
