# Generated by Django 2.2.6 on 2020-01-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0036_remove_profile_finish_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_survey',
            field=models.BooleanField(default=False),
        ),
    ]
