# Generated by Django 2.2.6 on 2019-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
