# Generated by Django 2.2.7 on 2019-11-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(default='Technology', max_length=30),
            preserve_default=False,
        ),
    ]
