# Generated by Django 2.2.7 on 2019-11-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_profile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(max_length=100),
        ),
    ]
