# Generated by Django 2.2.6 on 2019-12-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191205_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='tot_late',
            new_name='late',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='tot_rate',
            new_name='rate',
        ),
    ]
