# Generated by Django 2.2.6 on 2019-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191220_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationitem',
            name='read_at',
        ),
        migrations.AddField(
            model_name='notificationitem',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
