# Generated by Django 2.2.6 on 2020-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191222_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
