# Generated by Django 2.2.6 on 2020-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_statistics_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationitem',
            name='type',
            field=models.CharField(choices=[('MR', 'Match Request'), ('CS', 'Complete Survey'), ('MC', 'Match Canceled'), ('MA', 'Match Accept'), ('MD', 'Match Deny/Reject'), ('DA', 'Deleted Account')], max_length=100),
        ),
    ]
