# Generated by Django 2.2.6 on 2020-01-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200111_2335'),
        ('account', '0018_auto_20200112_1216'),
    ]

    operations = [
    ]
