# Generated by Django 2.2.6 on 2019-12-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_statistics_no_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='avg_rate',
            new_name='tot_num',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='late_num',
            new_name='tot_rate',
        ),
    ]
