# Generated by Django 2.2.6 on 2019-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notificationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationitem',
            name='match_name',
            field=models.CharField(default='drew', max_length=254),
            preserve_default=False,
        ),
    ]
