# Generated by Django 2.2.6 on 2019-12-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_notificationitem_match_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationitem',
            name='read_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
