# Generated by Django 3.0 on 2019-12-18 21:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_auto_20191208_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Industry', 'Industry'), ('Role', 'Role'), ('Year In School', 'Year In School')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
