# Generated by Django 3.0 on 2019-12-19 03:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0007_remove_profile_match_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='match_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Industry', 'Industry'), ('Role', 'Role'), ('Year In School', 'Year In School')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
