# Generated by Django 3.0 on 2019-12-20 20:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0009_auto_20191219_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry1',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting')], default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry2',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry3',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filter_by',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Industry', 'Industry'), ('Role', 'Role'), ('Year In School', 'Year In School'), ('Similar Interviews', 'Similar # of Interviews'), ('Most Interviews', 'Most # Interviews'), ('Rating', 'Rating')], max_length=50),
        ),
    ]
