# Generated by Django 3.0 on 2019-12-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0012_auto_20191220_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry_choice_1',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting'), ('None', 'None')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry_choice_2',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Consulting', 'Consulting'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
