# Generated by Django 3.0 on 2019-12-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0016_auto_20191220_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry_match',
            field=models.CharField(choices=[('Industry 1', 'Industry 1'), ('Industry 2', 'Industry 2'), ('Both', 'Both')], default='Industry 1', max_length=30),
        ),
    ]
