# Generated by Django 3.0 on 2019-12-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0005_profile_phone'),
        ('onboard', '0023_auto_20191221_0313'),
    ]

    operations = [
    ]
