# Generated by Django 2.2.6 on 2019-12-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0025_auto_20191221_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_email',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
