# Generated by Django 2.2.6 on 2020-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0027_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_idle',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
