# Generated by Django 2.2.6 on 2020-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0029_auto_20200102_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
