# Generated by Django 2.2.6 on 2020-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0030_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_names',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
