# Generated by Django 2.2.6 on 2020-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0034_auto_20200109_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finish_survey',
            field=models.BooleanField(default=False),
        ),
    ]
