# Generated by Django 2.2.6 on 2020-01-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0035_profile_finish_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='finish_survey',
        ),
    ]
